Patch spawn positions
CrowdedMods/CrowdedMod pull request #19
Opened 2021-01-31 17:40 UTC by simonkellly

Patched it so that you spawn in the normal spawn locations as if you have playerId mod 10

2021-02-01 13:20 UTC, DorCoMaNdO commented
No need to have Prefix with a bool return value if you're always going to return true, you can change it to void and remove the return.

2021-02-01 13:32 UTC, Galster-dev requested changes
very hard review !

2021-02-01 13:32 UTC, Galster-dev commented on CrowdedMod/Patches/GenericPatches.cs
> +		    public static bool Prefix(ShipStatus __instance, [HarmonyArgument(0)] ref int playerId, [HarmonyArgument(1)] ref int numPlayer, [HarmonyArgument(2)] bool initialSpawn)
you can leave only required arguments here, harmony will patch it anyway (unless it's overrided)

2021-02-01 13:32 UTC, Galster-dev commented on CrowdedMod/Patches/GenericPatches.cs
> +			return true;
you don't need to use bool-prefix if it always returns true. void-prefix will do the same by [comment](https://github.com/CrowdedMods/CrowdedMod/pull/19#issuecomment-770851779)

2021-02-01 13:32 UTC, Galster-dev commented on CrowdedMod/Patches/GenericPatches.cs
> +			if (numPlayer >= 10) numPlayer = 10;
why `>=`, not just `>`?

2021-02-02 13:56 UTC, Galster-dev approved these changes

2021-02-02 13:56 UTC, merged